In [31]:
df = pd.read_csv("kc_house_data.csv")
df.head()

id  date  price  bedrooms  \
0  7129300520,"20141013T000000",221900,3,1,1180,5...   NaN    NaN       NaN   
1  6414100192,"20141209T000000",538000,3,2.25,257...   NaN    NaN       NaN   
2  5631500400,"20150225T000000",180000,2,1,770,10...   NaN    NaN       NaN   
3  2487200875,"20141209T000000",604000,4,3,1960,5...   NaN    NaN       NaN   
4  1954400510,"20150218T000000",510000,3,2,1680,8...   NaN    NaN       NaN   

   bathrooms  sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0        NaN          NaN       NaN     NaN         NaN   NaN  ...    NaN   
1        NaN          NaN       NaN     NaN         NaN   NaN  ...    NaN   
2        NaN          NaN       NaN     NaN         NaN   NaN  ...    NaN   
3        NaN          NaN       NaN     NaN         NaN   NaN  ...    NaN   
4        NaN          NaN       NaN     NaN         NaN   NaN  ...    NaN   

   sqft_above  sqft_basement  yr_built  yr_renovated  zipcode  lat  long  \
0         NaN            NaN       NaN           NaN      NaN  NaN   NaN   
1         NaN            NaN       NaN           NaN      NaN  NaN   NaN   
2         NaN            NaN       NaN           NaN      NaN  NaN   NaN   
3         NaN            NaN       NaN           NaN      NaN  NaN   NaN   
4         NaN            NaN       NaN           NaN      NaN  NaN   NaN   

   sqft_living15  sqft_lot15  
0            NaN         NaN  
1            NaN         NaN  
2            NaN         NaN  
3            NaN         NaN  
4            NaN         NaN  

[5 rows x 21 columns]

In [39]:
def create_delta_renovated(df, col1, col2):
    df['delta_renovated'] = df.apply(lambda x: x[col1] - x[col2] if x[col1] != 0 else 0, axis=1)
    return df

df = create_delta_renovated(df, 'yr_renovated', 'yr_built')
display(df['delta_renovated'].unique())
df.head()


array([nan])

id date  price  bedrooms  \
0  7129300520,"20141013T000000",221900,3,1,1180,5...  NaT    NaN       NaN   
1  6414100192,"20141209T000000",538000,3,2.25,257...  NaT    NaN       NaN   
2  5631500400,"20150225T000000",180000,2,1,770,10...  NaT    NaN       NaN   
3  2487200875,"20141209T000000",604000,4,3,1960,5...  NaT    NaN       NaN   
4  1954400510,"20150218T000000",510000,3,2,1680,8...  NaT    NaN       NaN   

   bathrooms  sqft_living  sqft_lot  floors  waterfront  view  ...  yr_built  \
0        NaN          NaN       NaN     NaN         NaN   NaN  ...       NaN   
1        NaN          NaN       NaN     NaN         NaN   NaN  ...       NaN   
2        NaN          NaN       NaN     NaN         NaN   NaN  ...       NaN   
3        NaN          NaN       NaN     NaN         NaN   NaN  ...       NaN   
4        NaN          NaN       NaN     NaN         NaN   NaN  ...       NaN   

   yr_renovated  zipcode  lat  long  sqft_living15  sqft_lot15  \
0           NaN      NaN  NaN   NaN            NaN         NaN   
1           NaN      NaN  NaN   NaN            NaN         NaN   
2           NaN      NaN  NaN   NaN            NaN         NaN   
3           NaN      NaN  NaN   NaN            NaN         NaN   
4           NaN      NaN  NaN   NaN            NaN         NaN   

   delta_renovated  year_sold  month_sold  
0              NaN        NaN         NaN  
1              NaN        NaN         NaN  
2              NaN        NaN         NaN  
3              NaN        NaN         NaN  
4              NaN        NaN         NaN  

[5 rows x 24 columns]

In [40]:
import pandas as pd
import numpy as np

# Загрузка данных
df = pd.read_csv('kc_house_data.csv')

# Создание признака "Год продажи"
df['year_sold'] = pd.DatetimeIndex(df['date']).year

# Создание признака "Месяц продажи"
df['month_sold'] = pd.DatetimeIndex(df['date']).month

# Удаление признаков "date", "zipcode", "lat", "long"
df = df.drop(columns=['date', 'zipcode', 'lat', 'long'])


In [46]:
class Delta:
    def __init__(self, col1, col2):
        self.col1 = col1
        self.col2 = col2
    
    def create_delta_renovated(self, df):
        df['delta_renovated'] = df.apply(lambda x: x[self.col1] - x[self.col2] if x[self.col1] != 0 else 0, axis=1)
        return df


delta = Delta('yr_renovated', 'yr_built')
df = delta.create_delta_renovated(df)
display(df['delta_renovated'].unique())
df.head()
array([  0,  40,  72,  45,  60,  99,  78,  97,  74,  34,  63, 101,  26,
        49,  89,  62,  51, 110, 102,  27,  38,  22,  53,  85,  31,  77,
        93,  18,  66,  21,  91,  75,  44,  28,  48,  46,  29,  58,  70,
        32,  56,  65,  47,  57,   9,  35,  82,  76,  61,  59,  87,  30,
        86, 108, 103,  79,  12,  37,  98,  16,  69,  94,  33,  43,  39,
        88,  71, 109, 114,  81,  84,  64, 104,  68,  90,  83,  41,  73,
        52,  36,  24, 105,  67,  15,  55,  42,  25,  17,   8,  50,  19,
        23,  54,  20,  80,  96, 100,  95,  92, 113,  11,   6,  14,  13,
       107,  10], dtype=int64)

array([nan])

NameError: name 'array' is not defined